POST http://localhost:3000/clients
Content-Type: application/json

{
  "checklist": ["Algum texto aqui"],
  "date": "2024-02-25",
  "email": "novo_cliente@example.com",
  "id": "0001",
  "name": "Novo Cliente",
  "observation": "Novo cliente adicionado via requisição HTTP.",
  "telefone": "(99) 99999-9999"
}

###

GET http://localhost:3000/clients
Content-Type: application/json

###

DELETE http://localhost:3000/clients/1
Content-Type: application/json
